name: flutter_training
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mockito: ^5.4.2
  riverpod_annotation: ^2.1.5
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  blendthink_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.4

flutter_gen:
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true

  assets:
    - images/
