// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_training/test/view/weather_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_training/model/weather_forecast.dart' as _i5;
import 'package:flutter_training/model/weather_request.dart' as _i6;
import 'package:flutter_training/service/weather_service.dart' as _i2;
import 'package:flutter_training/utils/api/result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherService extends _i1.Mock implements _i2.WeatherService {
  @override
  _i3.Future<_i4.Result<_i5.WeatherForecast, String>> fetchWeather(
          _i6.WeatherRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchWeather,
          [request],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.WeatherForecast, String>>.value(
            _i7.dummyValue<_i4.Result<_i5.WeatherForecast, String>>(
          this,
          Invocation.method(
            #fetchWeather,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<_i5.WeatherForecast, String>>.value(
                _i7.dummyValue<_i4.Result<_i5.WeatherForecast, String>>(
          this,
          Invocation.method(
            #fetchWeather,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.WeatherForecast, String>>);
}
