name: Review Assign

on:
  pull_request:
    types: [ opened, ready_for_review ]

env:
  REVIEWERS: Yamasaki-pan961, morikann, trm11tkr

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ env.REVIEWERS }}
          ready-comment: 'Ready for review :rocket:'
